### ISSUE TITLE
Smaller inputs?

### ISSUE THREAD

**Issue by jeremyworger** [VillainNumberOne/multi-example-texture-synthesis#1]
Hi there, do you have any examples of using small pixelated inputs? Like 64x64 and smaller?
Such as the tile inputs from: https://github.com/mxgmn/WaveFunctionCollapse  
Just curious to know what you think the output would look like before I hop into trying to run this.

**Comment by VillainNumberOne** [comment]
Hi! I don't have any pre-made examples, but it definitely should be possible to use small inputs. If memory serves, the smallest possible input is 16x16 with K=0 in feature extractor (number of layers in gaussian pyramid - 1). 

I took this 23x24 sample from https://github.com/mxgmn/WaveFunctionCollapse:
![MoreFlowers](https://user-images.githubusercontent.com/66220826/211153979-a97ad532-6ec7-446a-8bd7-f4f13ac052fa.png)

And here is the result i got after 20 iterations (I'dont think more iterations can solve the problem):
![generated flowers](https://user-images.githubusercontent.com/66220826/211153673-b15488d1-0709-41e2-a4af-7aab008c1766.jpg)

The objection of this project was to generate photoreal natural-looking textures, and "photoreal" isn't quite the definition of such inputs. So, although it's possible, I can't guarantee that results will please you

**Comment by VillainNumberOne** [comment]
I've upscaled the initial sample to 128x128 and used K=2. Here is 256x256 result I got after 10 iterations:
![upscaled](https://user-images.githubusercontent.com/66220826/211154942-fadcc4fb-54df-415b-829d-0f75045f34ba.png)

So, if you want to get something adequate from the program at all costs, you can try to upscale inputs and run for larger number of iterations, but I beleave there must exist more efficient methods for the task
